[build]
builder = "herokuish"

[deploy]
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[env]
RAILS_ENV = "production"
RAILS_SERVE_STATIC_FILES = "true"
