---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/hackernews/top_stories":
    get:
      summary: Lista as principais notícias do Hackernews
      tags:
        - Hackernews
      responses:
        "200":
          description: notícias encontradas
  "/api/v1/hackernews/{id}/relevant_comments":
    get:
      summary: Lista comentários relevantes de uma notícia
      tags:
        - Hackernews
      parameters:
        - name: id
          in: path
          description: ID da notícia
          required: true
          schema:
            type: string
      responses:
        "200":
          description: comentários encontrados
        "404":
          description: notícia não encontrada
  "/api/v1/hackernews/search":
    get:
      summary: Busca notícias por palavra-chave
      tags:
        - Hackernews
      parameters:
        - name: query
          in: query
          description: Palavra-chave para busca
          schema:
            type: string
      responses:
        "200":
          description: notícias encontradas
        "422":
          description: parâmetro ausente ou inválido

  "/api/v1/hackernews/replies_at_comments":
    get:
      summary: Lista respostas para uma lista de comentários
      tags:
        - Hackernews
      parameters:
        - name: ids
          in: query
          description: Lista de IDs de comentários separados por vírgula (apenas números e vírgulas, sem espaços)
          required: true
          schema:
            type: string
            pattern: '^\d+(,\d+)*$'
      responses:
        "200":
          description: respostas encontradas
        "422":
          description: parâmetro ids ausente ou inválido
servers:
  - url: http://localhost:3000
    variables:
      defaultHost:
        default: http://localhost:3000
  - url: https://desafio-tecnico-beep-api-production.up.railway.app/
    variables:
      defaultHost:
        default: https://desafio-tecnico-beep-api-production.up.railway.app/
