development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  url: <%= ENV['UPSTASH_REDIS_REST_URL'] %>
  password: <%= ENV['UPSTASH_REDIS_REST_TOKEN'] %>
  channel_prefix: desafio_tecnico_beep_production
